### ISSUE TITLE
Find Open API which could be used in building a useful application

### ISSUE THREAD

**Issue by Riyu44** [Sopra-Banking-Software-Interns/API-Application#1]
Find APIs which could be utilized to make an API application, string them up in the chat here:
https://account.cloudmersive.com/
https://prismic.io/blog/13-best-api-project-ideas

Look into these and continue the thread

**Comment by Tushar-2510** [comment]
> Find APIs which could be utilized to make an API application, string them up in the chat here: https://account.cloudmersive.com/ https://prismic.io/blog/13-best-api-project-ideas
https://rapidapi.com/collection/list-of-free-apis
> 
> Look into these and continue the thread

**Comment by Tushar-2510** [comment]
> Find APIs which could be utilized to make an API application, string them up in the chat here: https://account.cloudmersive.com/ https://prismic.io/blog/13-best-api-project-ideas
https://rapidapi.com/collection/list-of-free-apis
https://ipapi.co/
https://wit.ai/docs/http/20230215/
https://spoonacular.com/food-api/docs
https://developer.nytimes.com/apis
https://www.themealdb.com/api.php
https://www.thecocktaildb.com/api.php
https://developer.oxforddictionaries.com/documentation
> 
> Look into these and continue the thread

**Comment by Riyu44** [comment]
Here's the plan:
Use the ipapi to get the ip address of the user and use it to get the country region which would then be utilized to get the language of the country and send a message to the user in their native language
